services:
  eureka-server:
    network_mode: host
    ports: []
  auth-db:
    network_mode: host
    command: ["postgres", "-p", "5433"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U resolvenow -d auth_db -p 5433"]
  complaint-db:
    network_mode: host
    command: ["postgres", "-p", "5434"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U resolvenow -d complaint_db -p 5434"]
  assignment-db:
    network_mode: host
    command: ["postgres", "-p", "5435"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U resolvenow -d assignment_db -p 5435"]
  notification-db:
    network_mode: host
    command: ["postgres", "-p", "5436"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U resolvenow -d notification_db -p 5436"]
  auth-service:
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/auth_db
      EUREKA_URL: http://localhost:8761/eureka
  complaint-service:
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5434/complaint_db
      EUREKA_URL: http://localhost:8761/eureka
  assignment-service:
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5435/assignment_db
      EUREKA_URL: http://localhost:8761/eureka
  notification-service:
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5436/notification_db
      EUREKA_URL: http://localhost:8761/eureka
  api-gateway:
    network_mode: host
    ports: []
    environment:
      EUREKA_URL: http://localhost:8761/eureka
