services:
  eureka-server:
    build: { context: ., args: { MODULE: eureka-server } }
    ports: ["8761:8761"]
  auth-db:
    image: postgres:16-alpine
    environment: { POSTGRES_DB: auth_db, POSTGRES_USER: resolvenow, POSTGRES_PASSWORD: resolvenow }
    volumes: [auth-data:/var/lib/postgresql/data]
  complaint-db:
    image: postgres:16-alpine
    environment: { POSTGRES_DB: complaint_db, POSTGRES_USER: resolvenow, POSTGRES_PASSWORD: resolvenow }
    volumes: [complaint-data:/var/lib/postgresql/data]
  assignment-db:
    image: postgres:16-alpine
    environment: { POSTGRES_DB: assignment_db, POSTGRES_USER: resolvenow, POSTGRES_PASSWORD: resolvenow }
    volumes: [assignment-data:/var/lib/postgresql/data]
  notification-db:
    image: postgres:16-alpine
    environment: { POSTGRES_DB: notification_db, POSTGRES_USER: resolvenow, POSTGRES_PASSWORD: resolvenow }
    volumes: [notification-data:/var/lib/postgresql/data]
  auth-service:
    build: { context: ., args: { MODULE: auth-service } }
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      EUREKA_URL: http://eureka-server:8761/eureka
    depends_on: [auth-db, eureka-server]
  complaint-service:
    build: { context: ., args: { MODULE: complaint-service } }
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://complaint-db:5432/complaint_db
      EUREKA_URL: http://eureka-server:8761/eureka
    depends_on: [complaint-db, eureka-server]
  assignment-service:
    build: { context: ., args: { MODULE: assignment-service } }
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://assignment-db:5432/assignment_db
      EUREKA_URL: http://eureka-server:8761/eureka
    depends_on: [assignment-db, eureka-server]
  notification-service:
    build: { context: ., args: { MODULE: notification-service } }
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:5432/notification_db
      EUREKA_URL: http://eureka-server:8761/eureka
    depends_on: [notification-db, eureka-server]
  api-gateway:
    build: { context: ., args: { MODULE: api-gateway } }
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
    ports: ["8080:8080"]
    depends_on: [eureka-server, auth-service, complaint-service, assignment-service, notification-service]
volumes:
  auth-data:
  complaint-data:
  assignment-data:
  notification-data:
